config/routes.rb
Rails.application.routes.draw do
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'users#new', :as => 'sign_up'

  root :to => 'chores#index'

  resources :chores, :cleanings, :users, :sessions, :households
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chore.rb
class Chore < ApplicationRecord
  has_one :household
  has_many :cleanings

  validates_presence_of :name
  validates_presence_of :household_id
end

app/models/cleaning.rb
class Cleaning < ApplicationRecord
  belongs_to :chore
  belongs_to :user

  validates_presence_of :date
  validates_presence_of :chore_id
  validates_presence_of :user_id
end

app/models/household.rb
class Household < ApplicationRecord
  has_many :users
  has_many :chores
end

app/models/user.rb
class User < ApplicationRecord
  has_one :household
  has_many :cleanings

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :name

  def self.authenticate(email, password)
    user = find_by_email(email)

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  before_action :require_login

  private

  def require_login
    unless current_user
      redirect_to log_in_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    @chore = Chore.find_by(id: params[:id])
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)
    @chore.household_id = current_user.household_id

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render :show, status: :created, location: @chore }
      else
        format.html { render :new }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    respond_to do |format|
      if @chore.update(chore_params)
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { render :show, status: :ok, location: @chore }
      else
        format.html { render :edit }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore.destroy
    respond_to do |format|
      format.html { redirect_to chores_url, notice: 'Chore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chore
      @chore = Chore.find(params[:id])
    end

    def chore_params
      params.require(:chore).permit(:name, :household_id)
    end
end

app/controllers/cleanings_controller.rb
class CleaningsController < ApplicationController

  def create
    chore = Chore.find( cleaning_params[:chore_id] )
    @cleaning = Cleaning.new( { :date => DateTime.now, :chore_id => chore.id, :user_id => current_user.id } )

    logger.debug "Cleaning created: #{@cleaning.inspect}"

    respond_to do |format|
      if @cleaning.save
        format.html { redirect_to @cleaning.chore, notice: 'Cleaning was added successfully.' }
        format.json { render :show, status: :created, location: @cleaning.chore }
      else
        format.html { render chore_path( params[:chore] ) }
        format.json { render json: @cleaning.errors, status: :unprocessable_entity }
      end
    end

  end

  private

  def cleaning_params
    params.require(:cleaning).permit(:chore_id)
  end

end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController

  def show
    @household = Household.find_by_id(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    household = Household.new
    household.save
    @user.household_id = household.id

    if @user.save
      redirect_to root_url, :notice => 'Signed up!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/cleanings_helper.rb
module CleaningsHelper
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chores/_form.html.erb
<%= form_for(chore) do |f| %>
  <% if chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing Chore</h1>

<%= render 'form', chore: @chore %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h1>Chores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chores.each do |chore| %>
      <tr>
        <td><%= link_to chore.name, chore %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New Chore</h1>

<%= render 'form', chore: @chore %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
  <h1><%= @chore.name %></h1>

  <h2>List of cleanings</h2>
  <div class="cleanings">
    <% @chore.cleanings.each do |cleaning| %>
        <p>Cleaning time: <%= cleaning[:date].strftime('%A, %d.%m.%Y at %H:%M') %>, cleaned by: <%= User.find( cleaning[:user_id] ).name %> </p>
    <% end %>
    <%= link_to 'Add cleaning', cleanings_path( cleaning: { chore_id: @chore.id } ), method: :post %>
  </div>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Destroy', @chore, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', chores_path %>

app/views/households/show.erb
<h1>Members of this household</h1>
<div class="users">
  <% @household.users.each do |user| %>
    <p><%= user.name %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cleanm8</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>

    <div id="user_nav">
      <% if current_user %>
          Logged in as <%= current_user.name %>.
          <%= link_to 'Log out', log_out_path %>
          <%= link_to 'View members of household', Household.find_by_id( current_user.household_id ) %>
      <% else %>
          <%= link_to 'Sign up', sign_up_path %> or
          <%= link_to 'Log in', log_in_path %>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>